add fermi to cc
lsst/templates pull request #105
Opened 2020-12-14 22:48 UTC by womullan

2020-12-15 14:51 UTC, ehneilsen approved these changes
Looks good

2020-12-15 15:39 UTC, drphilmarshall approved these changes
Looks good to me. I'll chase down the BNL equivalent too, but this can be merged in the meantime I think. Thanks!

2020-12-16 18:22 UTC, drphilmarshall requested changes
Easy addition of BNL copyright statement to match Fermilab's.

2020-12-16 18:22 UTC, drphilmarshall commented on project_templates/technote_aastex/cookiecutter.json
> +    "Fermi Research Alliance, LLC",
```suggestion
    "Fermi Research Alliance, LLC",
    "Brookhaven Science Associates, LLC",
```

2020-12-16 18:22 UTC, drphilmarshall commented on project_templates/technote_latex/cookiecutter.json
> +    "Fermi Research Alliance, LLC",
```suggestion
    "Fermi Research Alliance, LLC",
    "Brookhaven Science Associates, LLC",
```

2020-12-16 18:22 UTC, drphilmarshall commented on project_templates/technote_rst/cookiecutter.json
> +    "Fermi Research Alliance, LLC",
```suggestion
    "Fermi Research Alliance, LLC",
    "Brookhaven Science Associates, LLC",
```

2020-12-16 22:29 UTC, womullan commented on project_templates/technote_latex/cookiecutter.json
> +    "Fermi Research Alliance, LLC",
added alphabetically

2020-12-16 22:31 UTC, womullan commented
@jonathansick is this ok?

2020-12-16 22:52 UTC, jonathansick approved these changes
Yep, this works.

2020-12-17 15:20 UTC, merged